name: Angular CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🟢 Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: 📦 Install dependencies
      run: npm install

    - name: 🔨 Build Angular app
      run: npm run build --if-present

    - name: ✅ Run tests
      run: npm run test --if-present -- --watch=false --browsers=ChromeHeadless
